In [1]:
import pandas as pd
import duckdb

conn = duckdb.connect('mydb.db') # create an in-memory database

In [2]:
conn.sql("drop table if exists TBB_U")

conn.sql("""CREATE TABLE TBB_U AS SELECT * FROM 'A10_TBB_UNION.parquet'""")

In [3]:
conn.sql("SELECT * FROM TBB_U LIMIT 20").df()

                                                  TBB
0   GGTACTTTGAGAGCTATTACTTCTACTACTACTGCTACTACTTCTG...
1   TATGATGTTTCTCCACACTTCTCTACTACTGACTTTGATTCTGGTG...
2   GAAGATTTGGCTTCATTTGCTGAATTGTTGCAATCTACTGGTATCT...
3   TCTACTGCTACTACTAATTTGGCTTCTCCACAATCTTTGTTTGATT...
4   GAATTTCCACCAGGTCATGAACAATGGGATCCATTGTTTCCAACTA...
5   TCTATTCCACAAGACTTTGATGCTTTGTTTGATTTGACTGCTAATT...
6   AGAGCTAGAAATACTGAAGCTGCTAGGAAATCTAGAGCTAGGAAAT...
7   TTGTTGCAGAATGGTTTGTTGAATCCATCTAATGGTAAATCTCCAT...
8   CCATCTCCAATGTTGTCTGATGACTTTGGTTCTGAACAATGGGATT...
9   CCATCTTCTTCTCCATCTTTGCCAGCTCCATCTGCTCATCATCAGA...
10  CAACAGAATAGATTGAGACAATTGCAACAACAACCATCTCAATTGG...
11  AGAACTAATCCATTGCCACCAATTGTTGTTGAAGATCCATCTGATG...
12  GAGAAGACTAGATTGTTTGCTATGGCTGAAATGTTTCCTAAAGGTT...
13  TGGTGGGATACTTTGTCTCAATTCTTTCAAGTTCATTTGGATGGTG...
14  TCTTCTTCTTCTCCACCACCATCTCCAAGACCACCACCATTCTCTT...
15  AGATCTACTCCATTGACTCCAATTATTGTTCAATCTAATGATGATT...
16  GGTGTTGCTGCTGCTTCTGTTCCAAGAGGTACTTGGGCATTTCCAG...
17  ACTGATATGGAATTGGCTCCAGGTCATGAAGAATGGGATTCTTTGT...
18  CCATCTTCTACTGAATCTCCAGATACTTCTCCAAGATATCATTCTT...
19  GCTCAAATCTTGCAAGCTATTGGTCATCCAGCTTTGTCTTCTGCTT...

How many RPTR BCs map to multiple tiles? single tiles?