In [1]:
import pandas as pd
import numpy as np

In [5]:
test_string = """Assembled reads ...................: 29,459,066 / 30,868,032 (95.436%)
Discarded reads ...................: 0 / 30,868,032 (0.000%)
Not assembled reads ...............: 1,408,966 / 30,868,032 (4.564%)
Assembled reads file...............: results/RPTR_2_180_S68.fastq.gz.assembled.fastq
Discarded reads file...............: results/RPTR_2_180_S68.fastq.gz.discarded.fastq
Unassembled forward reads file.....: results/RPTR_2_180_S68.fastq.gz.unassembled.forward.fastq
Unassembled reverse reads file.....: results/RPTR_2_180_S68.fastq.gz.unassembled.reverse.fastq
bash pear.sh AD_4_180_S61_R1_001.fastq.gz AD_4_180_S61_R2_001.fastq.gz results/AD_4_180_S61.fastq.gz"""

In [6]:
test_string.startswith('Assembled reads ....')

True

In [14]:
test_string.split('/')[4].split('.')[0]

'RPTR_2_180_S68'

In [2]:
test_path = 'test_file.txt'
counts_list = []
names_list = []

with open (test_path, 'r') as p:
    for line in p:
#         print(line)
        if line.startswith('Assembled reads ....'):
#             print('found assembled read counts')
            counts = [line.split(' ')[3],line.split(' ')[5]]
            counts_list.append(counts)
        elif line.startswith('Assembled reads file...'):
            filename = line.split('/')[1].split('.')[0]
            names_list.append(filename)
            
            
test_dict = dict(zip(names_list, counts_list))
print(test_dict)

{'RPTR_2_180_S68': ['29,459,066', '30,868,032']}

In [3]:
pd.DataFrame.from_dict(test_dict, orient='index', columns=['Assembled', 'Total'])

                 Assembled       Total
RPTR_2_180_S68  29,459,066  30,868,032

In [4]:
pear_path = '/global/scratch/projects/fc_mvslab/data/sequencing/CZB_Apr2024/20240425/EC_Ciber2/slurm-18411976.out'
counts_list = []
names_list = []

with open (pear_path, 'r') as p:
    for line in p:
        if line.startswith('Assembled reads ....'):
            counts = [line.split(' ')[5],line.split(' ')[3]]
            counts_list.append(counts)
        elif line.startswith('Assembled reads file...'):
            filename = line.split('/')[1].split('.')[0]
            names_list.append(filename)
            
            
pear_dict = dict(zip(names_list, counts_list))
# print(pear_dict)

In [5]:
allthings = pd.DataFrame.from_dict(pear_dict, orient='index', columns=['Total','Assembled'])
allthings

                      Total    Assembled
RPTR_3_240_S75   28,533,299   27,239,158
RPTR_4_15_S79    28,895,257   27,600,242
RPTR_4_30_S80    29,313,499   28,002,280
AD_2_0_S44       29,212,873   28,596,028
RPTR_2_240_S69   30,239,860   28,851,158
RPTR_3_0_S70     30,584,585   29,208,826
RPTR_2_0_S63     30,664,329   29,281,808
RPTR_2_180_S68   30,868,032   29,459,066
RPTR_3_180_S74   31,378,023   29,946,720
AD_4_10_S58      31,725,692   31,068,838
RPTR_3_5_S71     32,204,354   30,746,712
RPTR_4_10_S78    32,742,281   31,258,832
AD_3_15_S53      32,895,150   32,209,522
AD_4_0_S56       33,220,932   32,525,715
AD_3_240_S55     33,349,632   32,676,395
AD_4_15_S59      33,428,966   32,731,675
AD_4_240_S62     35,129,689   34,409,399
RPTR_4_5_S77     35,345,633   33,756,214
RPTR_2_10_S65    35,648,049   34,031,691
RPTR_3_10_S72    35,595,194   33,975,374
RPTR_4_240_S82   36,164,871   34,554,681
AD_3_0_S50       36,482,067   35,713,078
RPTR_4_180_S81   37,441,995   35,752,625
AD_2_30_S48      38,373,639   37,578,617
RPTR_2_30_S67    26,338,421   25,144,079
AD_2_5_S45       27,435,063   26,861,003
AD_3_10_S52      29,795,764   29,170,896
AD_4_5_S57       30,105,481   29,479,549
RPTR_2_5_S64     31,314,046   29,897,603
AD_3_5_S51       34,922,862   34,198,696
RPTR_3_15_S73    35,178,306   33,586,682
AD_2_10_S46      32,027,127   31,356,537
AD_3_180_S54     32,830,117   32,166,856
AD_2_180_S49     38,582,509   37,785,429
RPTR_4_0_S76     37,433,719   35,752,202
AD_2_15_S47      35,234,224   34,497,180
AD_4_30_S60      37,820,625   37,031,059
AD_4_180_S61     43,589,073   42,680,103
RPTR_2_15_S66   323,641,185  309,116,948

In [6]:
allthings.describe()

             Total   Assembled
count           39          39
unique          39          39
top     28,533,299  27,239,158
freq             1           1