In [2]:
import pandas as pd
import duckdb
conn = duckdb.connect('/global/scratch/users/empchase/Seq_analysis/mydb.db') # create an in-memory database

In [3]:
a101 = pd.read_csv('A10_1_tbcmapDEEP.csv', header=0)
a101.head()

,Unnamed: 0,Tiles,AD BCs,RPTR BCs,Cat,BC Pairs
0,0,GGTGTTACTGCTGCTGATGCTGAATCTTTGGTTGCTGATCACTTCT...,ACCTCAAAGGC,CCGCTCATAGTTTT,GGTGTTACTGCTGCTGATGCTGAATCTTTGGTTGCTGATCACTTCT...,ACCTCAAAGGC-CCGCTCATAGTTTT
1,1,CAACAAGTTTCTGTTTCTGCTGCTCATGCTCCACATCCAAGATTGT...,AATTGTTAACA,TCAGCGTCTCTCGC,CAACAAGTTTCTGTTTCTGCTGCTCATGCTCCACATCCAAGATTGT...,AATTGTTAACA-TCAGCGTCTCTCGC
2,2,TCTCATTATAGACCACCAGTTCCATTGTTTAATAATTCTACTACTA...,GCACTCAAGGT,TGAGTCACTAATCA,TCTCATTATAGACCACCAGTTCCATTGTTTAATAATTCTACTACTA...,GCACTCAAGGT-TGAGTCACTAATCA
3,3,CAACCAGATTCTGCTAATATGAATATTGCTGACTTTGAAGAATTTA...,TAAATATACCC,TTACAATTAGCACT,CAACCAGATTCTGCTAATATGAATATTGCTGACTTTGAAGAATTTA...,TAAATATACCC-TTACAATTAGCACT
4,4,AGAGCTGGTCCATCTCCATTGTTGCAAGATTTGGCTGCTAGATGTC...,TCGGGCCTTCT,TTGATTCTTCTTCG,AGAGCTGGTCCATCTCCATTGTTGCAAGATTTGGCTGCTAGATGTC...,TCGGGCCTTCT-TTGATTCTTCTTCG

In [4]:
a102 = pd.read_csv('A10_2_tbcmapDEEP.csv', header=0)
a102.head()

,Unnamed: 0,Tiles,AD BCs,RPTR BCs,Cat,BC Pairs
0,0,CATACTCCATCTACTGATGCTTTGATTAATCCAGCTGCTTTGATGT...,CAAAAGTACAG,TAGGCGCTTGTACA,CATACTCCATCTACTGATGCTTTGATTAATCCAGCTGCTTTGATGT...,CAAAAGTACAG-TAGGCGCTTGTACA
1,1,TCTCAATCTTCTTGGTTGCCATCTTCTTCTCCATCTTTGCCAGCTC...,TACGCGGAATC,ATTGTTGTTACACG,TCTCAATCTTCTTGGTTGCCATCTTCTTCTCCATCTTTGCCAGCTC...,TACGCGGAATC-ATTGTTGTTACACG
2,2,AATCATTTGCCACAACAATGTACTCCATCTTCTGTTCAATCTCCAC...,ATCCGTACAGC,GTTTTACCTTTGTC,AATCATTTGCCACAACAATGTACTCCATCTTCTGTTCAATCTCCAC...,ATCCGTACAGC-GTTTTACCTTTGTC
3,3,AAATCATTTGAAGCTAGGATTCCAAGAAGACATATGGTTATGACTT...,CAGAGATATCA,TAAAGAGGATCTAA,AAATCATTTGAAGCTAGGATTCCAAGAAGACATATGGTTATGACTT...,CAGAGATATCA-TAAAGAGGATCTAA
4,4,AATGGTATGGACTTCTCTGCTGCTGAAGCATTTACTAGAATGAAGA...,GGAGTGTTCAT,TCGAACCATCCTGA,AATGGTATGGACTTCTCTGCTGCTGAAGCATTTACTAGAATGAAGA...,GGAGTGTTCAT-TCGAACCATCCTGA

In [6]:
adcol1 = a101['AD BCs'].copy()
a101['TileADBC'] = a101['Tiles'].str.cat(adcol1, sep="-")
a101.head()

,Unnamed: 0,Tiles,AD BCs,RPTR BCs,Cat,BC Pairs,TileADBC
0,0,GGTGTTACTGCTGCTGATGCTGAATCTTTGGTTGCTGATCACTTCT...,ACCTCAAAGGC,CCGCTCATAGTTTT,GGTGTTACTGCTGCTGATGCTGAATCTTTGGTTGCTGATCACTTCT...,ACCTCAAAGGC-CCGCTCATAGTTTT,GGTGTTACTGCTGCTGATGCTGAATCTTTGGTTGCTGATCACTTCT...
1,1,CAACAAGTTTCTGTTTCTGCTGCTCATGCTCCACATCCAAGATTGT...,AATTGTTAACA,TCAGCGTCTCTCGC,CAACAAGTTTCTGTTTCTGCTGCTCATGCTCCACATCCAAGATTGT...,AATTGTTAACA-TCAGCGTCTCTCGC,CAACAAGTTTCTGTTTCTGCTGCTCATGCTCCACATCCAAGATTGT...
2,2,TCTCATTATAGACCACCAGTTCCATTGTTTAATAATTCTACTACTA...,GCACTCAAGGT,TGAGTCACTAATCA,TCTCATTATAGACCACCAGTTCCATTGTTTAATAATTCTACTACTA...,GCACTCAAGGT-TGAGTCACTAATCA,TCTCATTATAGACCACCAGTTCCATTGTTTAATAATTCTACTACTA...
3,3,CAACCAGATTCTGCTAATATGAATATTGCTGACTTTGAAGAATTTA...,TAAATATACCC,TTACAATTAGCACT,CAACCAGATTCTGCTAATATGAATATTGCTGACTTTGAAGAATTTA...,TAAATATACCC-TTACAATTAGCACT,CAACCAGATTCTGCTAATATGAATATTGCTGACTTTGAAGAATTTA...
4,4,AGAGCTGGTCCATCTCCATTGTTGCAAGATTTGGCTGCTAGATGTC...,TCGGGCCTTCT,TTGATTCTTCTTCG,AGAGCTGGTCCATCTCCATTGTTGCAAGATTTGGCTGCTAGATGTC...,TCGGGCCTTCT-TTGATTCTTCTTCG,AGAGCTGGTCCATCTCCATTGTTGCAAGATTTGGCTGCTAGATGTC...

In [7]:
adcol2 = a102['AD BCs'].copy()
a102['TileADBC'] = a102['Tiles'].str.cat(adcol2, sep="-")
a102.head()

,Unnamed: 0,Tiles,AD BCs,RPTR BCs,Cat,BC Pairs,TileADBC
0,0,CATACTCCATCTACTGATGCTTTGATTAATCCAGCTGCTTTGATGT...,CAAAAGTACAG,TAGGCGCTTGTACA,CATACTCCATCTACTGATGCTTTGATTAATCCAGCTGCTTTGATGT...,CAAAAGTACAG-TAGGCGCTTGTACA,CATACTCCATCTACTGATGCTTTGATTAATCCAGCTGCTTTGATGT...
1,1,TCTCAATCTTCTTGGTTGCCATCTTCTTCTCCATCTTTGCCAGCTC...,TACGCGGAATC,ATTGTTGTTACACG,TCTCAATCTTCTTGGTTGCCATCTTCTTCTCCATCTTTGCCAGCTC...,TACGCGGAATC-ATTGTTGTTACACG,TCTCAATCTTCTTGGTTGCCATCTTCTTCTCCATCTTTGCCAGCTC...
2,2,AATCATTTGCCACAACAATGTACTCCATCTTCTGTTCAATCTCCAC...,ATCCGTACAGC,GTTTTACCTTTGTC,AATCATTTGCCACAACAATGTACTCCATCTTCTGTTCAATCTCCAC...,ATCCGTACAGC-GTTTTACCTTTGTC,AATCATTTGCCACAACAATGTACTCCATCTTCTGTTCAATCTCCAC...
3,3,AAATCATTTGAAGCTAGGATTCCAAGAAGACATATGGTTATGACTT...,CAGAGATATCA,TAAAGAGGATCTAA,AAATCATTTGAAGCTAGGATTCCAAGAAGACATATGGTTATGACTT...,CAGAGATATCA-TAAAGAGGATCTAA,AAATCATTTGAAGCTAGGATTCCAAGAAGACATATGGTTATGACTT...
4,4,AATGGTATGGACTTCTCTGCTGCTGAAGCATTTACTAGAATGAAGA...,GGAGTGTTCAT,TCGAACCATCCTGA,AATGGTATGGACTTCTCTGCTGCTGAAGCATTTACTAGAATGAAGA...,GGAGTGTTCAT-TCGAACCATCCTGA,AATGGTATGGACTTCTCTGCTGCTGAAGCATTTACTAGAATGAAGA...

In [9]:
conn.sql("drop table if exists TBB")


conn.sql("""CREATE TABLE TBB(
    Tiles VARCHAR,
    ADbc VARCHAR,
    RPTRbc VARCHAR,
    TBBs VARCHAR,
    TILEADBC VARCHAR);""")

conn.sql("""INSERT INTO TBB 
select Tiles, "AD BCs", "RPTR BCs", Cat, TileADBC 
from a101""") #maybe select distinct * from read_csv_auto... 

conn.sql("""INSERT INTO TBB 
select Tiles, "AD BCs", "RPTR BCs", Cat, TileADBC 
from a102""")

In [4]:
# conn.sql("drop table if exists TBB")


# conn.sql("""CREATE TABLE TBB(
#     Tiles VARCHAR,
#     ADbc VARCHAR,
#     RPTRbc VARCHAR,
#     TBBs VARCHAR);""")

# conn.sql("""INSERT INTO TBB 
# select Tiles, "AD BCs", "RPTR BCs", Cat 
# from read_csv_auto ('A10_1_tbcmapDEEP.csv', header=True)""") #maybe select distinct * from read_csv_auto... 

# conn.sql("""INSERT INTO TBB 
# select Tiles, "AD BCs", "RPTR BCs", Cat 
# from read_csv_auto ('A10_2_tbcmapDEEP.csv', header=True)""")

In [10]:
conn.sql("Select * from TBB limit 10").df() #limit is important, result lives in memory regardless of variable definition

,Tiles,ADbc,RPTRbc,TBBs,TILEADBC
0,GGTGTTACTGCTGCTGATGCTGAATCTTTGGTTGCTGATCACTTCT...,ACCTCAAAGGC,CCGCTCATAGTTTT,GGTGTTACTGCTGCTGATGCTGAATCTTTGGTTGCTGATCACTTCT...,GGTGTTACTGCTGCTGATGCTGAATCTTTGGTTGCTGATCACTTCT...
1,CAACAAGTTTCTGTTTCTGCTGCTCATGCTCCACATCCAAGATTGT...,AATTGTTAACA,TCAGCGTCTCTCGC,CAACAAGTTTCTGTTTCTGCTGCTCATGCTCCACATCCAAGATTGT...,CAACAAGTTTCTGTTTCTGCTGCTCATGCTCCACATCCAAGATTGT...
2,TCTCATTATAGACCACCAGTTCCATTGTTTAATAATTCTACTACTA...,GCACTCAAGGT,TGAGTCACTAATCA,TCTCATTATAGACCACCAGTTCCATTGTTTAATAATTCTACTACTA...,TCTCATTATAGACCACCAGTTCCATTGTTTAATAATTCTACTACTA...
3,CAACCAGATTCTGCTAATATGAATATTGCTGACTTTGAAGAATTTA...,TAAATATACCC,TTACAATTAGCACT,CAACCAGATTCTGCTAATATGAATATTGCTGACTTTGAAGAATTTA...,CAACCAGATTCTGCTAATATGAATATTGCTGACTTTGAAGAATTTA...
4,AGAGCTGGTCCATCTCCATTGTTGCAAGATTTGGCTGCTAGATGTC...,TCGGGCCTTCT,TTGATTCTTCTTCG,AGAGCTGGTCCATCTCCATTGTTGCAAGATTTGGCTGCTAGATGTC...,AGAGCTGGTCCATCTCCATTGTTGCAAGATTTGGCTGCTAGATGTC...
5,GATGATGCTGTTGTTGAATCATTCTTCTCTTCTTCTACTGATTCTA...,GTGCGCTAATT,GAATGCCCGTGACC,GATGATGCTGTTGTTGAATCATTCTTCTCTTCTTCTACTGATTCTA...,GATGATGCTGTTGTTGAATCATTCTTCTCTTCTTCTACTGATTCTA...
6,TCTAGGAAACAAAGAGCTGCTCCATTGACTCCAGTTATTCCAGAAT...,TATTCCGATCT,GATAGCACCGTTTG,TCTAGGAAACAAAGAGCTGCTCCATTGACTCCAGTTATTCCAGAAT...,TCTAGGAAACAAAGAGCTGCTCCATTGACTCCAGTTATTCCAGAAT...
7,TGGGATTCTTTGTTTCCAGCTAATGATCCATTCTCTGCTGCTTTGG...,GAGCTCACCTT,GAGGGGAGTATTTT,TGGGATTCTTTGTTTCCAGCTAATGATCCATTCTCTGCTGCTTTGG...,TGGGATTCTTTGTTTCCAGCTAATGATCCATTCTCTGCTGCTTTGG...
8,TTGGCTGGTGATCCATGGTATCCATTGTTTCCACAAGATGATCAAG...,ACGCTGCTGTG,CTCGGCTATTTACA,TTGGCTGGTGATCCATGGTATCCATTGTTTCCACAAGATGATCAAG...,TTGGCTGGTGATCCATGGTATCCATTGTTTCCACAAGATGATCAAG...
9,TCTTCTAGAAATTCTTCTCAACCACCATCTACTACTCCATTGCAAG...,GATGTAATGAC,AGCATAAAATACTA,TCTTCTAGAAATTCTTCTCAACCACCATCTACTACTCCATTGCAAG...,TCTTCTAGAAATTCTTCTCAACCACCATCTACTACTCCATTGCAAG...

In [6]:
conn.sql("COPY TBB TO 'trueunionTBB_deep.parquet' (FORMAT PARQUET);") #took ~1min